InsuranceClaim/Controllers/CustomerRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using InsuranceClaim.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Insurance.Domain;
using AutoMapper;
using System.Configuration;
using System.Globalization;
using Insurance.Service;
using System.Web.Configuration;
using Newtonsoft.Json.Linq;
using RestSharp;
using Newtonsoft.Json;
using System.Data.SqlClient;
using System.IO;
using System.Net;
using System.Web.Script.Serialization;
using System.Text;
using iTextSharp.text;
using iTextSharp.text.pdf;
using InsuranceClaim.Models;

namespace InsuranceClaim.Controllers
{
    public class CustomerRegistrationController : Controller
    {
        private ApplicationUserManager _userManager;
        string AdminEmail = WebConfigurationManager.AppSettings["AdminEmail"];
        string ZimnatEmail = WebConfigurationManager.AppSettings["ZimnatEmail"];
        public CustomerRegistrationController()
        {
            // UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // [Authorize(Roles = "Staff,Administrator")]

        public ActionResult Index(int id = 0)
        {
            // var res = MaxCustoermId();

            // var res = InsuranceContext.Query("select * from Customer").Select(x => new CustomerModel() { AddressLine1 = x.AddressLine1 }).ToList();

            // var roles = UserManager.GetRoles("Guest-1161@gmail.com").FirstOrDefault();


            if (id != -1) // -1 use for getting session value when click on back button
            {
                RemoveSession();
            }

            bool userLoggedin = (System.Web.HttpContext.Current.User != null) && System.Web.HttpContext.Current.User.Identity.IsAuthenticated;
            string path = Server.MapPath("~/Content/Countries.txt");
            var countries = System.IO.File.ReadAllText(path);
            var resultt = Newtonsoft.Json.JsonConvert.DeserializeObject<RootObject>(countries);
            ViewBag.Countries = resultt.countries.OrderBy(x => x.code.Replace("+", ""));

            //string paths = Server.MapPath("~/Content/Cities.txt");
            //var cities = System.IO.File.ReadAllText(paths);
            //var resultts = Newtonsoft.Json.JsonConvert.DeserializeObject<RootObjects>(cities);
            //ViewBag.Cities = resultts.cities;

            ViewBag.Cities = InsuranceContext.Cities.All();



            if (id > 0) // if staff try to edit Qutation
            {
                SetCustomerValueIntoSession(id); // here id represent to summardetialid during edit the Qutation
            }


            if (userLoggedin && id == 0)
            {
                var customerModel = new CustomerModel();
                var _User = UserManager.FindById(User.Identity.GetUserId().ToString());


                var _customerData = InsuranceContext.Customers.All(where: $"UserId ='{User.Identity.GetUserId().ToString()}'").FirstOrDefault();
                var customerData = (CustomerModel)Session["CustomerDataModal"];


                var role = UserManager.GetRoles(_User.Id.ToString()).FirstOrDefault();

                ViewBag.CurrentUserRole = role;

                if ((role != null && (role != "Staff" && role != "Renewals")))
                {
                    if (customerData != null)
                    {
                        var User = UserManager.FindById(customerData.UserID);
                        customerModel.AddressLine1 = customerData.AddressLine1;
                        customerModel.AddressLine2 = customerData.AddressLine2;
                        customerModel.City = customerData.City;
                        customerModel.Id = customerData.Id;
                        customerModel.Country = customerData.Country;
                        customerModel.Zipcode = customerData.Zipcode;
                        customerModel.Gender = customerData.Gender;
                        customerModel.PhoneNumber = customerData.PhoneNumber;
                        customerModel.NationalIdentificationNumber = customerData.NationalIdentificationNumber;
                        customerModel.DateOfBirth = customerData.DateOfBirth;
                        customerModel.EmailAddress = customerData.EmailAddress;
                        customerModel.FirstName = customerData.FirstName;
                        customerModel.LastName = customerData.LastName;
                        customerModel.CountryCode = customerData.CountryCode;
                        customerModel.IsCustomEmail = customerData.IsCustomEmail;
                    }
                    else
                    {
                        customerModel.AddressLine1 = _customerData.AddressLine1;
                        customerModel.AddressLine2 = _customerData.AddressLine2;
                        customerModel.City = _customerData.City;
                        customerModel.Id = _customerData.Id;
                        customerModel.Country = _customerData.Country;
                        customerModel.Zipcode = _customerData.Zipcode;
                        customerModel.Gender = _customerData.Gender;
                        customerModel.PhoneNumber = _User.PhoneNumber;
                        customerModel.NationalIdentificationNumber = _customerData.NationalIdentificationNumber;
                        customerModel.DateOfBirth = _customerData.DateOfBirth;
                        customerModel.EmailAddress = _User.Email;
                        customerModel.FirstName = _customerData.FirstName;
                        customerModel.LastName = _customerData.LastName;
                        customerModel.CountryCode = _customerData.Countrycode;
                        customerModel.CustomerId = _customerData.CustomerId;
                        customerModel.IsActive = _customerData.IsActive;
                        customerModel.UserID = _customerData.UserID;
                        customerModel.IsCustomEmail = _customerData.IsCustomEmail;
                    }
                    customerModel.Zipcode = "00263";

                    Session["CustomerDataModal"] = customerModel; // for admin
                }
                customerModel.Zipcode = "00263";
                RemoveSession();



                return View(customerModel);
            }
            else
            {
                var customerData = (CustomerModel)Session["CustomerDataModal"];
                var customerModel = new CustomerModel();
                customerModel.Zipcode = "00263";
                if (customerData != null)
                {
                    var User = UserManager.FindById(customerData.UserID);
                    customerModel.AddressLine1 = customerData.AddressLine1;
                    customerModel.AddressLine2 = customerData.AddressLine2;
                    customerModel.City = customerData.City;
                    customerModel.Id = customerData.Id;
                    customerModel.Country = customerData.Country;
                    customerModel.Zipcode = customerData.Zipcode;
                    customerModel.Gender = customerData.Gender;
                    customerModel.PhoneNumber = customerData.PhoneNumber;
                    customerModel.NationalIdentificationNumber = customerData.NationalIdentificationNumber;
                    customerModel.DateOfBirth = customerData.DateOfBirth;
                    customerModel.EmailAddress = customerData.EmailAddress;
                    customerModel.FirstName = customerData.FirstName;
                    customerModel.LastName = customerData.LastName;
                    customerModel.CountryCode = customerData.CountryCode;
                    customerModel.IsCustomEmail = customerData.IsCustomEmail;
                }
                return View(customerModel);
            }

        }


        public void SetCustomerValueIntoSession(int summaryId)
        {
            Session["ICEcashToken"] = null;
            Session["issummaryformvisited"] = true;
            Session["SummaryDetailId"] = summaryId;

            var summaryDetail = InsuranceContext.SummaryDetails.Single(summaryId);
            var Cusotmer = InsuranceContext.Customers.Single(summaryDetail.CustomerId);
            CustomerModel custModel = AutoMapper.Mapper.Map<Customer, CustomerModel>(Cusotmer);

            if (Cusotmer != null)
            {
                var dbUser = UserManager.Users.FirstOrDefault(c => c.Id == Cusotmer.UserID);
                if (dbUser != null)
                {
                    custModel.EmailAddress = dbUser.Email; ;
                }
            }
            Session["CustomerDataModal"] = custModel;
        }

        [HttpPost]
        public async Task<JsonResult> SaveCustomerData(CustomerModel model, string buttonUpdate)
        {
            if (ModelState.IsValid)
            {
                bool userLoggedin = (System.Web.HttpContext.Current.User != null) && System.Web.HttpContext.Current.User.Identity.IsAuthenticated;

                if (userLoggedin)
                {

                    //var AllUsers = UserManager.Users.ToList();
                    //var isExist = AllUsers.Any(p => p.Email.ToLower() == model.EmailAddress.ToLower() || p.UserName.ToLower() == model.EmailAddress);
                    //if (isExist)
                    //{

InsuranceClaim/Views/CustomerRegistration/Addvehicle.cshtml
@model  InsuranceClaim.Models.RiskDetailModel



<table>
    <tr>
        <th>Registration No</th>
        <th>Make</th>
        <th>Model</th>
        <th>Cubic Capacity</th>
        <th>Vehicle Year</th>
        <th>Engine Number</th>
        <th>Chasis Number</th>
        <th>Vehicle Usage</th>
        <th>Cover Type</th>
        <th>Suggested Value</th>
        <th>Sum Insured</th>
        <th>Premium</th>
        <th>Agent Commission</th>
        <th>Stamp Duty</th>
        <th>ZTSC Levy</th>
        <th>Radio License Cost</th>
        <th>Optional Covers</th>
        <th>Excess Type</th>
        <th>Excess</th>
    </tr>

   

</table>

InsuranceClaim/Views/CustomerRegistration/PreviewReceiptModule.cshtml
@model InsuranceClaim.Models.PreviewReceiptListModel
@{
    ViewBag.Title = "ReceiptModule";
    Layout = "~/Views/Shared/_InsuranceMain.cshtml";
}





<body>

    <div width="565" style="margin:0 auto; width:900px; font-family:arial;">
        <table width="565" border="0" cellspacing="0" cellpadding="5" style="border-collapse:collapse; width:100%">
            <tbody>
                <tr>
                    <th width="200" style="text-align:left;">
                        <img width="200" src="@Model.filepath/Images/geneinsure-logo1.png" style="width:290px;" />
                    </th>
                    <th align="right" style="text-align:right">
                        <div align="right" style="float:right">
                            <p style="font-size:12px; margin:0 0 3px 0;"><font size="2">Genetic Financial Services</font></p>
                            <p style="font-size:12px; margin:0 0 3px 0;"><font size="2">11 Routledge Street</font></p>
                            <p style="font-size:12px; margin:0 0 3px 0;"><font size="2">Milton Park</font></p>
                            <p style="font-size:12px; margin:0 0 3px 0;"><font size="2">Harare</font></p>
                        </div>
                    </th>
                </tr>
                <tr>
                    <td align="right" width="250" style="width:50%; text-align:left;">
                        <p style="margin:0 0 3px; padding:0 0; font-size:14px; color:#444;"><font size="2">@Model.CustomerName</font></p>
                        <p style="margin:0 0 3px; font-size:14px; color:#444;"><font size="2">@Model.Address1</font></p>
                        <p style="margin:0 0 3px; font-size:14px; color:#444;"><font size="2">@Model.Address2</font></p>
                    </td>
                    <td width="250" style="width:50%; text-align:left; font-size:15px;  word-break: break-all">
                        <div align="right" style="float:right; text-align:right; font-size:15px;  word-break: break-all">
                            <p style="margin:0 0 3px; font-size:14px; color:#444; word-break: break-all"><font size="2">GENEINSURE CONTACT</font></p>
                            <p style="margin:0 0 3px; font-size:14px; color:#444; word-break: break-all"><font size="2">Call us on : +263 867 722 33 44</font></p>
                            <p style="margin:0 0 3px; font-size:14px; color:#444; word-break: break-all"><font size="2">Whatsapp us on : +263 719 884 884 /+263 732 884 884</font></p>
                            <p style="margin:0 0 3px; font-size:14px; color:#000; word-break: break-all"><font size="2"><strong>Email us on: service@gene.co.zw</strong></font></p>
                        </div>
                    </td>
                </tr>
            </tbody>

        </table>

        <br />
        <table width="100%" border="1" cellspacing="0" cellpadding="5" style="border-collapse:collapse">
            <tr><td bgcolor="#000" colspan="2" style="background: black;color: white;text-align: center; padding: 5px; border-right:1px solid #ddd">GeneInsure</td></tr>
            <tr><td style="width:50%; height:20px; border: none;"></td><td style="width:50%; height:20px; border: none;"></td></tr>
            <tr><td style="width:50%; padding: 0 5px; border: none;"><font size="2">Call Center</font></td><td style="width:50%;  border: none;"></td></tr>
            <tr><td style="width:50%; height:20px;border: none;"></td><td style="width:50%; height:20px;border: none;"></td></tr>
            <tr><td bgcolor="#000" colspan="2" style="background: black;color: white;text-align: center; padding: 5px;border: none;">Receipt</td></tr>
            <tr><td style="width:50%; height:20px; border: none;"></td><td style="width:50%; height:20px;border: none;"></td></tr>
            <tr><td style="width:50%; padding: 0 5px;border: none;"><font size="2">DATE</font></td><td align="left" style="width:50%; padding: 0 5px; text-align:right;border: none;"><font size="2">@Model.Date</font></td></tr>
            <tr><td style="width:50%; height:20px; border: none;"></td><td style="width:50%; height:20px; border: none;"></td></tr>
            <tr><td style="width:50%; padding: 0 5px; border: none;"><font size="2">Receipt Number</font></td><td align="left" style="width:50%; padding: 0 5px; text-align:right; border: none;"><font size="2">@Model.Id   </font></td></tr>
            <tr><td style="width:50%; height:20px; border: none;"></td><td style="width:50%; height:20px;border: none;"></td></tr>
            <tr><td style="width:50%; padding: 0 5px;border: none;"><font size="2">Account Name</font></td><td align="left" style="width:50%; padding: 0 5px; text-align:right;border: none;"><font size="2">@Model.CustomerName</font></td></tr>
            <tr><td style="width:50%; height:20px;border: none;"></td><td style="width:50%; height:20px;border: none;"></td></tr>
            <tr><td style="width:50%; padding: 0 5px;border: none;"><font size="2">Receipt Amount</font></td><td align="left" style="width:50%; padding: 0 5px; text-align:right;border: none;"><font size="2">$@Model.AmountPaid</font></td></tr>
            <tr><td style="width:50%; height:20px;border: none;"></td><td style="width:50%; height:20px;border: none;"></td></tr>
            <tr><td style="width:50%; padding: 0 5px;border: none;"><font size="2">Balance</font></td><td align="left" style="width:50%; padding: 0 5px; text-align:right;border: none;"><font size="2">$@Model.PaymentDetails</font></td></tr>
            <tr><td style="width:50%; height:20px;border: none;"></td><td style="width:50%; height:20px;border: none;"></td></tr>
           
            <tr><td style="width:50%; padding: 0 5px;border: none;"><font size="2">Transaction Reference</font></td><td align="left" style="width:50%; padding: 0 5px; text-align:right;border: none;"><font size="2">@Model.TransactionReference</font></td></tr>
            <tr><td style="width:50%; height:20px;border: none;"></td><td style="width:50%; height:20px;border: none;"></td></tr>
            
             <tr><td style="width:50%; padding: 0 5px;border: none;"><font size="2">Payment Type</font></td><td align="left" style="width:50%; padding: 0 5px; text-align:right;border: none;"><font size="2">@Model.paymentMethodType</font></td></tr>
            <tr><td style="width:50%; height:20px;border: none; border-bottom: 1px solid black"></td><td style="width:50%; height:20px;border: none; border-bottom: 1px solid black"></td></tr>
        </table>
        <table style="width:100%;">
            <tbody>
                <tr>
                    <td align="left" style="padding:20px 0 10px; color:#444; font-size:14px; text-align:left"><font size="2">Thank you.</font></td>
                </tr>
                <tr>
                    <td align="left" style="padding:0px 0 10px; color:#444; font-size:14px; text-align:left"><font size="2">Yours Sincerely</font></td>
                </tr>
                <tr>
                    <td align="left" style="padding: 0 5px;  word-break: break-all; text-align:left"> <img width="50" src="@Model.filepath/Images/Geneinsuresign.png" /></td>
                </tr>
                <tr>
                    <td align="left" style="padding:7px 0 10px; color:#444; font-size:14px; text-align:left;"><font size="2">GENERAL MANAGER – SALES</font></td>
                </tr>

            </tbody>
        </table>
        <div class="print-btn" style="display:none">
            <div class="col-md-1">
                <input type="button" id="btnPrint" value="Print" class="btn btn-primary" />
            </div>
            <div class="col-md-1">
                <input type="button" id="btnSendEmail" value="Send Email" class="btn btn-primary" />
            </div>
        </div>


    </div>





</body>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(document).ready(function () {
        $('#btnPrint').click(function () {
            window.print();
        });
        $('#btnSendEmail').click(function () {
            debugger;
            var id = '@ViewBag.CurrentSaveId';
            $.ajax({
                url: "/CustomerRegistration/SendEmail",
                type: "POST",
                async: false,
                dataType: "json",
                data: { Id: id },
                success: function (data) {

                    debugger;
                    if (data == "Success") {
                        //toastr.success("Mail Sent Sucessfully")
                        window.location.href = '@Url.Action("ReceiptModule", "CustomerRegistration")';

                    }
                }
            })
        });
    })
</script>

InsuranceClaim/Views/CustomerRegistration/makepayment.cshtml
@using System.Web.Configuration;
@{
    ViewBag.Title = "makepayment";
    Layout = "~/Views/Shared/_InsuranceMain.cshtml";

}

<br />
@*<form  action="http://localhost:49873/CustomerRegistration/returnurl" class="paymentWidgets" data-brands="VISA MASTER AMEX"></form>*@
@*<form action="@Url.Action("returnurl", "CustomerRegistration")" class="paymentWidgets" data-brands="VISA MASTER AMEX"></form>*@


<form action="@WebConfigurationManager.AppSettings["urlPath"]/CustomerRegistration/returnurl" class="paymentWidgets" data-brands="VISA MASTER AMEX"></form>

<script src="https://test.oppwa.com/v1/paymentWidgets.js?checkoutId=@ViewBag.checkoutId"></script>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    var wpwlOptions = {
        onReady: function () {
            var numberOfInstallmentsHtml =
              '<div class="wpwl-wrapper wpwl-wrapper-custom" style="display:inline-block">' +
              '<input type="button" id=btnBack value="Back"/ style="background: #acacac;padding: 6px 12px;margin-bottom: 0;font-size: 14px;font-weight: 400;line-height: 1.42857143;">' +
              '<a style="display:none" id="previouselink" href="/CustomerRegistration/SummaryDetail" class="back"></a>'
              '</div>';
            $('form.wpwl-form-card').find('.wpwl-button').before(numberOfInstallmentsHtml);

            $("#btnBack").click(function () {
                $("#previouselink")[0].click();
            });
        }
    }
</script>